---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-ms-deployment
  labels:
    app: books-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-ms
  template:
    metadata:
      labels:
        app: books-ms
    spec:
      containers:
        - name: books-ms
          image: albjzan/books-ms:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: books-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-config-map
  namespace: default
data:
  NODE_ENV: production
  SERVER_PORT: "8081"
  DB_HOST: books-database
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: books
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC_NAME: notify
---
apiVersion: v1
kind: Service
metadata:
  name: books-ms-service
spec:
  type: NodePort
  selector:
    app: books-ms
  ports:
    - name: http
      port: 8081
      targetPort: 8081
