---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-ms-deployment
  labels:
    app: customers-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-ms
  template:
    metadata:
      labels:
        app: customers-ms
    spec:
      containers:
        - name: customers-ms
          image: albjzan/customers-ms:latest
          ports:
            - containerPort: 8081
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: NODE_ENV

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: SERVER_PORT

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: DB_PORT

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: DB_PASSWORD

            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: DB_DATABASE

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: KAFKA_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: envvar
                  key: KAFKA_TOPIC_NAME
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envvar
  namespace: default
data:
  NODE_ENV: production
  SERVER_PORT: "8081"
  DB_HOST: customers-database
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: customers
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC_NAME: notify
---
apiVersion: v1
kind: Service
metadata:
  name: customers-ms-service
spec:
  type: NodePort
  selector:
    app: customers-ms
  ports:
    - name: http
      port: 8081
      targetPort: 8081
