---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-ms-deployment
  labels:
    app: notifier-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier-ms
  template:
    metadata:
      labels:
        app: notifier-ms
    spec:
      containers:
        - name: notifier-ms
          image: albjzan/notifier-ms:latest
          envFrom:
            - configMapRef:
                name: notifier-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifier-config-map
  namespace: default
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC_NAME: notify
  BOT_TOKEN: 5071390558:AAHMvN9IYT84kI5vAoUVzDZC_ONf9Zeef1E
  TELEGRAM_ID: "144088919"
