---
fullnameOverride: customers-database
global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: postgres
initdbUser: postgres
initdbPassword: postgres
initdbScripts:
  dbinit.sql: |
    CREATE DATABASE "customers" OWNER postgres;
    \connect customers
    ALTER DATABASE "customers" SET TIMEZONE TO 'Europe/Rome';
    SET TIMEZONE TO 'Europe/Rome';

    CREATE TABLE "customer"
    (
        id character varying primary key,
        "firstName" character varying,
        "lastName" character varying,
        "privateAddress" character varying
    );

    ALTER TABLE "customer"
        OWNER to postgres;
