name: Build and push microservices to Docker Hub

on:
  push:

jobs:
  build-books-ms:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: books-ms
    steps:
      - uses: actions/checkout@v2
      - name: Get branch
        id: get_branch
        run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Get the commit SHA
        id: get_commit_sha
        run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")

      - name: Build books-ms image and push to Docker HUB
        uses: docker/build-push-action@v1.1.0
        with:
          path: books-ms/
          dockerfile: books-ms/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/books-ms
          tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}, latest

  build-customers-ms:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: customers-ms
    steps:
      - uses: actions/checkout@v2
      - name: Get branch
        id: get_branch
        run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Get the commit SHA
        id: get_commit_sha
        run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")

      - name: Build customers-ms image and push to Docker HUB
        uses: docker/build-push-action@v1.1.0
        with:
          path: customers-ms/
          dockerfile: customers-ms/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/customers-ms
          tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}, latest

  build-borrowing-ms:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: borrowing-ms
    steps:
      - uses: actions/checkout@v2
      - name: Get branch
        id: get_branch
        run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Get the commit SHA
        id: get_commit_sha
        run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")

      - name: Build borrowing-ms image and push to Docker HUB
        uses: docker/build-push-action@v1.1.0
        with:
          path: borrowing-ms/
          dockerfile: borrowing-ms/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/borrowing-ms
          tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}, latest
